# render.yaml

services:
  - type: web
    name: heros-and-minors-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://heros-and-minors-g2g3.onrender.com

  - type: web
    name: heros-and-minors-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: heros_and_minors
          property: connectionString